// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Usage } from "./Usage";

export type DailyProjectUsageReport = { reports: { [key in string]?: Usage }, components: { [key in string]?: { [key in string]?: Usage } }, 
/**
 * Per-user job counts. Empty when reading data from older instances.
 */
user_job_counts: { [key in string]?: bigint }, 
/**
 * Per-user wait seconds. Empty when reading data from older instances.
 */
user_wait_seconds: { [key in string]?: bigint }, 
/**
 * Scalar total — equals sum of user_job_counts when populated, otherwise
 * carries the value from older instances that lack per-user maps.
 */
num_jobs: bigint, 
/**
 * Scalar total — equals sum of user_wait_seconds when populated.
 */
total_wait_seconds: bigint, 
/**
 * Per-user sum of per-job expansion factors, in thousandths.
 */
user_expansion_milli: { [key in string]?: bigint }, 
/**
 * Scalar total — equals sum of user_expansion_milli when populated.
 */
total_expansion_milli: bigint, 
/**
 * Per-user total wall-clock runtime, in seconds. Not the same as usage,
 * which is weighted by the fraction of a node a job held.
 */
user_runtime_seconds: { [key in string]?: bigint }, 
/**
 * Scalar total — equals sum of user_runtime_seconds when populated.
 */
total_runtime_seconds: bigint, 
/**
 * Usage from attempts superseded by a requeue, per local user.
 */
requeue_reports: { [key in string]?: Usage }, 
/**
 * The same, broken down by resource component.
 */
requeue_components: { [key in string]?: { [key in string]?: Usage } }, 
/**
 * Per-user count of requeue *events* (superseded attempts, not jobs).
 */
user_requeue_events: { [key in string]?: bigint }, 
/**
 * Scalar total — equals sum of user_requeue_events when populated.
 */
num_requeue_events: bigint, 
/**
 * Per-user queue wait accumulated by superseded attempts.
 */
user_requeue_wait_seconds: { [key in string]?: bigint }, 
/**
 * Scalar total — equals sum of user_requeue_wait_seconds when populated.
 */
requeue_wait_seconds: bigint, 
/**
 * Requeue events by the terminal state of the superseded attempt. Sums to
 * `num_requeue_events`.
 */
requeue_states: { [key in string]?: bigint }, 
/**
 * Requeue usage by the terminal state of the superseded attempt. Sums to
 * `total_requeue_usage()`.
 */
requeue_state_usage: { [key in string]?: Usage }, 
/**
 * Reservation name → local user → usage consumed inside it.
 */
reservation_reports: { [key in string]?: { [key in string]?: Usage } }, 
/**
 * Reservation name → the part of the above from superseded attempts.
 */
reservation_requeue_usage: { [key in string]?: Usage }, 
/**
 * Reservation name → jobs that started inside it, counted as `num_jobs` is.
 */
reservation_jobs: { [key in string]?: bigint }, is_complete: boolean, };
