// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyProjectUsageReport } from "./DailyProjectUsageReport";

export type ProjectUsageReport = { project: string, reports: { [key in string]?: DailyProjectUsageReport }, 
/**
 * See the note on `DailyProjectUsageReport::reports` - written even when
 * empty, because release 0.92.0 cannot read a report without it.
 */
users: { [key in string]?: string }, };
