// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectUsageReport } from "./ProjectUsageReport";

/**
 * A portal-level usage report.
 *
 * Deserialised via `try_from` so a wire-supplied report cannot carry map keys that
 * disagree with its own `portal` field - `set_report` enforces that on the
 * programmatic path, but the derive inserted whatever it was given. It only matters
 * for a receiver that trusts the keys rather than re-inserting, but a type whose
 * invariant holds only on one of two construction paths is a trap. See
 * `docs/specifications/security-review-2.md` (finding R33).
 */
export type UsageReport = { portal: string, reports: { [key in string]?: ProjectUsageReport }, };
